language: node_js
node_js: node
cache:
  directories:
    - 'node_modules'
before_script:
  gpg --import ./test/example.priv.asc
script:
  - npm run cover
after_script:
  cat coverage/lcov.info | coveralls && gpg --yes --delete-secret-and-public-key email@example.com

